apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "ews-jwt-auth"
spec:
  jwtRules:
  - issuer: "https://us-south.appid.cloud.ibm.com/oauth/v4/<appid-tenant-id>"
    jwksUri: "https://us-south.appid.cloud.ibm.com/oauth/v4/<appid-tenant-id>/publickeys"
