apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-443
spec:
  applyOnForward: true
  ingress:
    - action: Allow
      destination:
        nets:
          - XX.XX.XX.XX/XX
        ports:
          - 443
      protocol: TCP
      source:
        nets:
          - XX.XX.XX.XX/XX
          - XX.XX.XX.XX/XX
          - XX.XX.XX.XX/XX 
  preDNAT: true
  selector: ibm.role=='worker_public'
  order: 1800
  types:
    - Ingress
