apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
$(kubectl -n kube-system get cm coredns -o jsonpath='{.data.Corefile}' | sed 's/^/    /')
    ibm.com 9.in-addr.arpa {
        forward . 9.0.128.50 9.0.130.50
        cache 30
        errors
    }
