apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
$(kubectl -n kube-system get cm coredns -o jsonpath='{.data.Corefile}' | sed 's/^/    /')
    ibm.com 9.in-addr.arpa {
        forward . XX.XX.XX.XX XX.XX.XX.XX 
        cache 30
        errors
    }
