apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alb-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: private-iks-k8s-nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/proxy-ssl-name: <internal-domain>
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"
    nginx.ingress.kubernetes.io/proxy-ssl-secret: istio-system/alb-certs
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: istio-system/alb-ca-certs
spec:
  tls:
  - hosts:
    - <internal-domain>
    secretName: istio-ingressgateway-internal-certs
  rules:
  - host: <internal-domain>
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 443
        path: /
        pathType: Prefix
